In [ ]:
from dotenv import load_dotenv
load_dotenv(override=True)

from wikifin_rag.agent_config import INSTRUCTIONS, OPENAI_MODEL, search_tool
from wikifin_rag.rag_utils import run_agent_loop

SyntaxError: invalid syntax (3344388321.py, line 6)

In [ ]:
q = "Wat is het verschil tussen een verzekering die alleen de betaalde premies teruggeeft en een verzekering die de verworven reserve uitbetaalt?"

In [ ]:
exchange_record, *_ = run_agent_loop(
    question=q,
    instructions=INSTRUCTIONS,
    tools=[search_tool],
    model=OPENAI_MODEL
)

In [ ]:
exchange_record.response

'Het verschil zit in wat de begunstigden krijgen als de verzekerde overlijdt vóór de einddatum van het contract:\n\n- **Terugbetaling van de betaalde premies**: de begunstigden krijgen de **premies terug die al betaald zijn**, **verminderd met kosten en taksen**.  \n- **Terugbetaling van de verworven reserve**: de begunstigden krijgen niet alleen de **betaalde premies** terug, maar ook de **intresten daarop** en eventuele **winstdeelnames**. Daardoor ligt het uitgekeerde bedrag meestal hoger.  \n\nBron: Wikifin, *Wat gebeurt er met mijn levensverzekering als ik overlijd voor het einde van het contract?* https://www.wikifin.be/nl/budget-betalen-lenen-en-verzekeren/verzekeren/familie/de-levens-en-overlijdensverzekering/wat-0'

In [2]:
from wikifin_rag.apps.dashboard.queries import get_judge_feedback, get_user_feedback, get_tokens, get_costs

In [3]:
from datetime import date, datetime
from dateutil.relativedelta import relativedelta

end_date = date.today()
start_date = end_date - relativedelta(year=3)

In [4]:
judge_feedback_df = get_judge_feedback(
    start_date=start_date,
    end_date=end_date
)
judge_feedback_df.head()

         relevance        date         day     week    month  year
0  PARTLY_RELEVANT  2025-04-10  2025-04-10  2025-14  2025-04  2025
1  PARTLY_RELEVANT  2024-02-25  2024-02-25  2024-08  2024-02  2024
2  PARTLY_RELEVANT  2024-01-10  2024-01-10  2024-02  2024-01  2024
3  PARTLY_RELEVANT  2025-04-16  2025-04-16  2025-15  2025-04  2025
4  PARTLY_RELEVANT  2024-09-07  2024-09-07  2024-36  2024-09  2024

In [5]:
user_feedback_df = get_user_feedback(
    start_date=start_date,
    end_date=end_date
)
user_feedback_df.head()

      score        date         day     week    month  year
0  POSITIVE  2024-04-21  2024-04-21  2024-16  2024-04  2024
1  POSITIVE  2025-04-10  2025-04-10  2025-14  2025-04  2025
2  POSITIVE  2025-09-17  2025-09-17  2025-37  2025-09  2025
3  NEGATIVE  2024-01-10  2024-01-10  2024-02  2024-01  2024
4  NEGATIVE  2025-04-16  2025-04-16  2025-15  2025-04  2025

In [6]:
user_feedback_df.score.value_counts()

score
POSITIVE    70
NEGATIVE    14
Name: count, dtype: int64

In [7]:
tokens_df = get_tokens(start_date=start_date, end_date=end_date)
tokens_df.tail(20)

,id,input_tokens,output_tokens,date,day,week,month,year
273,a73b3da8-c148-4dc7-8bea-11c1d975dee8,153,97,2026-06-05,2026-06-05,2026-22,2026-06,2026
274,53a4c885-ce63-4687-ac85-91b809fd5b56,197,223,2026-06-05,2026-06-05,2026-22,2026-06,2026
275,c0ca0ac5-b16b-4afd-b8c6-de01beb1c3b2,146,103,2024-01-14,2024-01-14,2024-02,2024-01,2024
276,55806ee0-4364-4468-9a64-7981b1e6bbe7,151,296,2024-01-14,2024-01-14,2024-02,2024-01,2024
277,ede57c72-e05d-4d7e-8780-124e2680a70d,86,124,2025-04-10,2025-04-10,2025-14,2025-04,2025
278,8e8b09ee-5a91-4c0a-abff-5d13c769a521,163,85,2025-04-16,2025-04-16,2025-15,2025-04,2025
279,9961bf23-7701-4b57-9ead-d00c7cd34e40,182,249,2025-04-10,2025-04-10,2025-14,2025-04,2025
280,ff3de0b8-ae44-482d-9b87-e887bcd3cc3f,54,196,2025-04-10,2025-04-10,2025-14,2025-04,2025
281,9efab182-15ff-4094-ab69-7760361dae72,141,110,2025-04-16,2025-04-16,2025-15,2025-04,2025
282,a48b422b-d5ab-4e6b-98b4-296220a642f8,130,54,2025-04-16,2025-04-16,2025-15,2025-04,2025
283,4170b2ea-d9ca-4fcb-831b-08d304fa00bc,162,282,2026-09-11,2026-09-11,2026-36,2026-09,2026
284,55bcd4b1-461e-4b7c-8373-c652b70886c1,112,75,2026-09-11,2026-09-11,2026-36,2026-09,2026
285,dd3898bc-943a-4af1-b9cb-5d7abadedaa4,115,228,2026-09-11,2026-09-11,2026-36,2026-09,2026
286,00e62d8c-4747-4308-bcfb-32d9f3253e96,105,116,2026-09-11,2026-09-11,2026-36,2026-09,2026
287,098ccadb-f1a0-4520-b179-74e5d902f7cb,186,104,2024-04-21,2024-04-21,2024-16,2024-04,2024
288,9bcd1529-ab55-4907-b497-5771ae23e988,158,130,2024-04-21,2024-04-21,2024-16,2024-04,2024
289,1d8a55ee-f78f-4733-994f-4b667308c09b,97,87,2024-04-21,2024-04-21,2024-16,2024-04,2024
290,f3da7d31-0e0b-4464-9db3-bbcf47c3bd54,109,261,2024-04-21,2024-04-21,2024-16,2024-04,2024
291,3f62edb2-43ea-4f89-824a-cef88e593f07,109,287,2025-09-17,2025-09-17,2025-37,2025-09,2025
292,9bbd07d1-397f-4a4f-85ee-f48c3bc1fe34,82,251,2025-09-17,2025-09-17,2025-37,2025-09,2025

In [9]:
costs_df = get_costs(start_date=start_date, end_date=end_date)
costs_df.tail(20)

,id,input_cost,output_cost,date,day,week,month,year
273,a73b3da8-c148-4dc7-8bea-11c1d975dee8,0.002776,0.001761,2026-06-05,2026-06-05,2026-22,2026-06,2026
274,53a4c885-ce63-4687-ac85-91b809fd5b56,0.004846,0.003691,2026-06-05,2026-06-05,2026-22,2026-06,2026
275,c0ca0ac5-b16b-4afd-b8c6-de01beb1c3b2,0.001992,0.004502,2024-01-14,2024-01-14,2024-02,2024-01,2024
276,55806ee0-4364-4468-9a64-7981b1e6bbe7,0.003190,0.004461,2024-01-14,2024-01-14,2024-02,2024-01,2024
277,ede57c72-e05d-4d7e-8780-124e2680a70d,0.004171,0.004083,2025-04-10,2025-04-10,2025-14,2025-04,2025
278,8e8b09ee-5a91-4c0a-abff-5d13c769a521,0.001117,0.004945,2025-04-16,2025-04-16,2025-15,2025-04,2025
279,9961bf23-7701-4b57-9ead-d00c7cd34e40,0.002527,0.001583,2025-04-10,2025-04-10,2025-14,2025-04,2025
280,ff3de0b8-ae44-482d-9b87-e887bcd3cc3f,0.001721,0.000793,2025-04-10,2025-04-10,2025-14,2025-04,2025
281,9efab182-15ff-4094-ab69-7760361dae72,0.002179,0.002199,2025-04-16,2025-04-16,2025-15,2025-04,2025
282,a48b422b-d5ab-4e6b-98b4-296220a642f8,0.000780,0.001307,2025-04-16,2025-04-16,2025-15,2025-04,2025
283,4170b2ea-d9ca-4fcb-831b-08d304fa00bc,0.000242,0.003084,2026-09-11,2026-09-11,2026-36,2026-09,2026
284,55bcd4b1-461e-4b7c-8373-c652b70886c1,0.001684,0.000349,2026-09-11,2026-09-11,2026-36,2026-09,2026
285,dd3898bc-943a-4af1-b9cb-5d7abadedaa4,0.004911,0.001299,2026-09-11,2026-09-11,2026-36,2026-09,2026
286,00e62d8c-4747-4308-bcfb-32d9f3253e96,0.004289,0.004249,2026-09-11,2026-09-11,2026-36,2026-09,2026
287,098ccadb-f1a0-4520-b179-74e5d902f7cb,0.000282,0.000322,2024-04-21,2024-04-21,2024-16,2024-04,2024
288,9bcd1529-ab55-4907-b497-5771ae23e988,0.000176,0.000958,2024-04-21,2024-04-21,2024-16,2024-04,2024
289,1d8a55ee-f78f-4733-994f-4b667308c09b,0.000874,0.002175,2024-04-21,2024-04-21,2024-16,2024-04,2024
290,f3da7d31-0e0b-4464-9db3-bbcf47c3bd54,0.003561,0.003557,2024-04-21,2024-04-21,2024-16,2024-04,2024
291,3f62edb2-43ea-4f89-824a-cef88e593f07,0.002853,0.000461,2025-09-17,2025-09-17,2025-37,2025-09,2025
292,9bbd07d1-397f-4a4f-85ee-f48c3bc1fe34,0.001919,0.001189,2025-09-17,2025-09-17,2025-37,2025-09,2025